name: Component tests

on:
  pull_request:

jobs:
  component-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 10  # Optional: specify a pnpm version

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
